server:
  port: 8083

spring:
  application:
    name: donor-service

  datasource:
    url: jdbc:mysql://localhost:3307/bloodgram
    username: root
    password: anurag
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      register-with-eureka: true;
      fetch-registry: true

jwt:
  secret: ${BLOODGRAM_JWT_KEY:fallback-super-secret-key-for-dev-only}
  expiration: 3600000