server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/**

    config:
      enabled: false

jwt:
  secret: ${BLOODGRAM_JWT_KEY:fallback-super-secret-key-for-dev-only}
  expiration: 3600000